---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - mail
  when: ansible_os_family == "Debian"

- name: Install msmtp and mailx
  apt:
    name:
      - msmtp
      - msmtp-mta
      - bsd-mailx
    state: present
  tags:
    - mail
  notify: test mail
  when: ansible_os_family == "Debian"

- name: Install msmtp and mailx
  pacman:
    name:
      - msmtp
      - msmtp-mta
      - mailutils
    state: present
  when: ansible_os_family == "Archlinux"

- name: Copy mstprc conf file
  template:
    src: templates/etc/msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: 0640
  tags:
    - mail
  notify: test mail

- name: Copy aliases conf file
  template:
    src: templates/etc/aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  tags:
    - mail
  notify: test mail

- name: Template systemd email service
  template:
    src: etc/systemd/system/status-email-user@.service.j2
    dest: /etc/systemd/system/status-email-user@.service
    owner: root
    group: root
    mode: 0644
  when: msmtp_enable_systemd_notifications == True
  tags:
    - mail

- name: Copy systemd email script
  copy:
    src: usr/local/sbin/systemd-email
    dest: /usr/local/sbin/systemd-email
    owner: root
    group: root
    mode: 0755
  when: msmtp_enable_systemd_notifications == True
  tags:
    - mail
