---

# Author: Adham Helal
#
# Objective: Deploy msmtp

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - mail
  when: ansible_os_family == "Debian"

- name: Install msmtp and mailx
  apt:
    name:
      - msmtp
      - msmtp-mta
      - bsd-mailx
    state: present
  tags:
    - mail
  notify: test mail
  when: ansible_os_family == "Debian"

- name: Install msmtp and mailx
  pacman:
    name:
      - msmtp
      - msmtp-mta
      - mailutils
    state: present
  when: ansible_os_family == "Archlinux"

- name: Copy mstprc conf file
  template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: 0644
  tags:
    - mail
  notify: test mail

- name: Copy aliases conf file
  template:
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  tags:
    - mail
  notify: test mail
